In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib as plt
import bs4 as bs
import requests
import datetime

In [2]:
#grab a list of tickers and include the general S&P ticker GSPC
resp = requests.get('http://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
soup = bs.BeautifulSoup(resp.text,'lxml')
table = soup.find('table', {'class': 'wikitable sortable'})
tickers = ['GSPC']
for row in table.findAll('tr')[1:]:
    ticker=row.findAll('td')[0].text    
    tickers.append(ticker)

In [3]:
#clean ticker list
tickers = [ticks.replace('\n', '') for ticks in tickers]
#tickers

In [4]:
stock_data = pd.DataFrame()
df_list = []
for ticker in tickers:
    ticker_data = yf.download(ticker)
    ticker_data['Ticker'] = ticker
    df_list = [stock_data,ticker_data]
    stock_data = pd.concat(df_list,ignore_index=False)

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['GSPC']: Exception('%ticker%: No timezone found, symbol may be delisted')

[*********************100%%**********************]  1 of 1 completed

C:\Users\brads\AppData\Local\Temp\ipykernel_15884\2043126397.py:7: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  stock_data = pd.concat(df_list,ignore_index=False)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['BRK.B']: Exception('%ticker%: No timezone found, symbol may be delisted')

C:\Users\brads\AppData\Local\Temp\ipykernel_15884\2043126397.py:7: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  stock_data = pd.concat(df_list,ignore_index=False)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 1925-10-06 -> 2024-09-12)')

C:\Users\brads\AppData\Local\Temp\ipykernel_15884\2043126397.py:7: FutureWarning: The behavior of array concatenation with empty entries is deprecated. In a future version, this will no longer exclude empty items when determining the result dtype. To retain the old behavior, exclude the empty entries before the concat operation.
  stock_data = pd.concat(df_list,ignore_index=False)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [5]:
company_data = pd.DataFrame()
df_list = []
tickers_nonGSPC = tickers[1:]
for ticker in tickers_nonGSPC:
    ticker_data = yf.Ticker(ticker).info
    df= pd.DataFrame.from_dict(ticker_data,orient='index')
    df = df.transpose()
    df['Ticker']=ticker
    df_list = [company_data,df]
    company_data = pd.concat(df_list,ignore_index=False)

In [22]:
pd.set_option("display.max_columns", None)

In [104]:
#drop columns that do not interest us
simp_company_data = company_data[['Ticker','industry','sector','fullTimeEmployees','totalCash','ebitda','totalDebt','totalRevenue','dividendYield','trailingPE','forwardPE','averageVolume10days','fiftyTwoWeekLow','fiftyTwoWeekHigh','profitMargins','sharesOutstanding','sharesShort','sharesShortPriorMonth','heldPercentInsiders','heldPercentInstitutions','shortRatio','bookValue','priceToBook','trailingEps','forwardEps','recommendationKey','recommendationMean','numberOfAnalystOpinions','returnOnEquity','freeCashflow','operatingCashflow','revenueGrowth','grossMargins','ebitdaMargins','operatingMargins','earningsQuarterlyGrowth','earningsGrowth']]
#simp_company_data

In [7]:
#create a DF that indicates the industry 
sector_ind_join = simp_company_data[['Ticker','industry','sector']]

In [15]:

stock_data = stock_data.reset_index()

In [16]:
#join it to stock data so that I can perform comparison analysis
stock_data_new = pd.merge(stock_data,sector_ind_join,on='Ticker',how='left')

In [17]:
stock_data_new

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,industry,sector
0,1962-01-02,0.000000,3.553512,3.448997,3.475125,0.570977,254509.0,MMM,Conglomerates,Industrials
1,1962-01-03,0.000000,3.501254,3.416336,3.501254,0.575270,505190.0,MMM,Conglomerates,Industrials
2,1962-01-04,0.000000,3.560044,3.501254,3.501254,0.575270,254509.0,MMM,Conglomerates,Industrials
3,1962-01-05,0.000000,3.488190,3.396739,3.409804,0.560245,376979.0,MMM,Conglomerates,Industrials
4,1962-01-08,0.000000,3.416336,3.370610,3.390207,0.557025,399942.0,MMM,Conglomerates,Industrials
...,...,...,...,...,...,...,...,...,...,...
4233040,2024-09-06,187.460007,190.440002,187.059998,189.229996,189.229996,2710100.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare
4233041,2024-09-09,190.550003,193.610001,190.089996,191.729996,191.729996,2652700.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare
4233042,2024-09-10,191.729996,192.770004,187.820007,191.360001,191.360001,2675600.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare
4233043,2024-09-11,190.710007,191.149994,186.440002,189.990005,189.990005,1387900.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare
4233044,2024-09-12,189.979996,190.675003,187.139999,188.309998,188.309998,179572.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare

In [18]:
#create float column to then be able to perform weighted price comparisons
stock_data_new['Float'] = stock_data_new['Adj Close']*stock_data_new['Volume']
stock_data_new

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,industry,sector,Float
0,1962-01-02,0.000000,3.553512,3.448997,3.475125,0.570977,254509.0,MMM,Conglomerates,Industrials,1.453188e+05
1,1962-01-03,0.000000,3.501254,3.416336,3.501254,0.575270,505190.0,MMM,Conglomerates,Industrials,2.906207e+05
2,1962-01-04,0.000000,3.560044,3.501254,3.501254,0.575270,254509.0,MMM,Conglomerates,Industrials,1.464114e+05
3,1962-01-05,0.000000,3.488190,3.396739,3.409804,0.560245,376979.0,MMM,Conglomerates,Industrials,2.112004e+05
4,1962-01-08,0.000000,3.416336,3.370610,3.390207,0.557025,399942.0,MMM,Conglomerates,Industrials,2.227776e+05
...,...,...,...,...,...,...,...,...,...,...,...
4233040,2024-09-06,187.460007,190.440002,187.059998,189.229996,189.229996,2710100.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,5.128322e+08
4233041,2024-09-09,190.550003,193.610001,190.089996,191.729996,191.729996,2652700.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,5.086022e+08
4233042,2024-09-10,191.729996,192.770004,187.820007,191.360001,191.360001,2675600.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,5.120028e+08
4233043,2024-09-11,190.710007,191.149994,186.440002,189.990005,189.990005,1387900.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,2.636871e+08
4233044,2024-09-12,189.979996,190.675003,187.139999,188.309998,188.309998,179572.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,3.381520e+07

In [26]:
#create industry comparison dataframe
#Float by industry and date
industry_WA = stock_data_new.groupby(['industry','Date']).sum('Float')
#Weighted Average Stock Price
industry_WA['industry_WASP']=industry_WA['Float']/industry_WA['Volume']
industry_WA = industry_WA.reset_index()
industry_WA

,industry,Date,Open,High,Low,Close,Adj Close,Volume,Float,industry_WASP
0,Advertising Agencies,1980-03-17,0.000000,2.373264,2.315972,2.315972,0.989285,68800.0,3.224211e+04,0.468635
1,Advertising Agencies,1980-03-18,0.000000,2.355903,2.309028,2.309028,0.985808,409200.0,1.762590e+05,0.430740
2,Advertising Agencies,1980-03-19,0.000000,2.371528,2.324653,2.324653,0.991893,155200.0,6.896613e+04,0.444369
3,Advertising Agencies,1980-03-20,0.000000,2.362847,2.315972,2.315972,0.989285,40000.0,1.799640e+04,0.449910
4,Advertising Agencies,1980-03-21,0.000000,2.347222,2.300347,2.300347,0.983201,573600.0,2.291990e+05,0.399580
...,...,...,...,...,...,...,...,...,...,...
1240358,Waste Management,2024-09-06,414.009995,416.600006,407.430008,407.550003,407.550003,3382900.0,6.906073e+08,204.146537
1240359,Waste Management,2024-09-09,409.619995,416.330002,408.139999,413.760010,413.760010,3172700.0,6.585917e+08,207.580839
1240360,Waste Management,2024-09-10,414.759995,417.100006,411.350006,414.559998,414.559998,2855400.0,5.932697e+08,207.771148
1240361,Waste Management,2024-09-11,412.270004,413.880005,404.850006,412.440002,412.440002,2201200.0,4.547042e+08,206.571066
1240362,Waste Management,2024-09-12,411.330002,411.480011,408.065002,410.400101,410.400101,352076.0,7.240797e+07,205.660068

In [25]:
#create sector comparison dataframe
#Float by sector and date
sector_WA = stock_data_new.groupby(['sector','Date']).sum('Float')
#Weighted Average Stock Price
sector_WA['sector_WASP']=sector_WA['Float']/sector_WA['Volume']
sector_WA = sector_WA.reset_index()
sector_WA

,sector,Date,Open,High,Low,Close,Adj Close,Volume,Float,sector_WASP
0,Basic Materials,1972-06-01,0.000000,7.294257,7.254722,7.274490,1.085975,74617.0,8.103223e+04,1.085975
1,Basic Materials,1972-06-02,7.294257,7.393096,7.294257,7.353560,1.097779,227645.0,2.499039e+05,1.097779
2,Basic Materials,1972-06-05,7.353560,7.363444,7.333793,7.333793,1.094828,96117.0,1.052316e+05,1.094828
3,Basic Materials,1972-06-06,7.333793,7.343677,7.294257,7.314025,1.091877,77146.0,8.423391e+04,1.091877
4,Basic Materials,1972-06-07,7.284374,7.284374,7.185535,7.185535,1.072696,121411.0,1.302370e+05,1.072696
...,...,...,...,...,...,...,...,...,...,...
165570,Utilities,2024-09-06,2658.160027,2669.689007,2620.549997,2630.090029,2628.578783,115575700.0,7.473926e+09,64.666934
165571,Utilities,2024-09-09,2639.719999,2668.429987,2618.230005,2660.909994,2659.984522,115753800.0,7.242589e+09,62.568908
165572,Utilities,2024-09-10,2667.920008,2693.545002,2645.550003,2673.850010,2673.180012,124326500.0,7.597838e+09,61.111979
165573,Utilities,2024-09-11,2672.060001,2698.999992,2636.074999,2687.559984,2687.559984,127289600.0,8.497510e+09,66.757303
165574,Utilities,2024-09-12,2678.555006,2705.834892,2664.860014,2687.816000,2687.816000,18403142.0,1.197932e+09,65.093883

In [33]:
#create a copy and merge stock data with industry trends
stock_data_new_copy = stock_data_new
stock_data_comb = pd.merge(stock_data_new,industry_WA[['industry','Date','industry_WASP']],on=['industry','Date'],how='left')

In [35]:
#create a copy and merge stock data with sector trends

stock_data_comb = pd.merge(stock_data_comb,sector_WA[['sector','Date','sector_WASP']],on=['sector','Date'],how='left')

In [36]:
stock_data_comb

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,industry,sector,Float,industry_WASP,sector_WASP
0,1962-01-02,0.000000,3.553512,3.448997,3.475125,0.570977,254509.0,MMM,Conglomerates,Industrials,1.453188e+05,0.638807,0.273300
1,1962-01-03,0.000000,3.501254,3.416336,3.501254,0.575270,505190.0,MMM,Conglomerates,Industrials,2.906207e+05,0.646071,0.299794
2,1962-01-04,0.000000,3.560044,3.501254,3.501254,0.575270,254509.0,MMM,Conglomerates,Industrials,1.464114e+05,0.690303,0.272775
3,1962-01-05,0.000000,3.488190,3.396739,3.409804,0.560245,376979.0,MMM,Conglomerates,Industrials,2.112004e+05,0.613105,0.312549
4,1962-01-08,0.000000,3.416336,3.370610,3.390207,0.557025,399942.0,MMM,Conglomerates,Industrials,2.227776e+05,0.654572,0.343272
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233040,2024-09-06,187.460007,190.440002,187.059998,189.229996,189.229996,2710100.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,5.128322e+08,51.834088,129.458493
4233041,2024-09-09,190.550003,193.610001,190.089996,191.729996,191.729996,2652700.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,5.086022e+08,51.908567,125.389561
4233042,2024-09-10,191.729996,192.770004,187.820007,191.360001,191.360001,2675600.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,5.120028e+08,47.581649,123.880025
4233043,2024-09-11,190.710007,191.149994,186.440002,189.990005,189.990005,1387900.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,2.636871e+08,36.842058,127.353239
4233044,2024-09-12,189.979996,190.675003,187.139999,188.309998,188.309998,179572.0,ZTS,Drug Manufacturers - Specialty & Generic,Healthcare,3.381520e+07,41.358184,104.330760

In [40]:
from fredapi import Fred
fred = Fred(api_key='01036b83bac73a4eb10a26ca80f7dd3a')

In [69]:
data_GDP = fred.get_series('GDP').reset_index()
data_unemp_rate = fred.get_series('unrate').reset_index()
data_consumercredit = fred.get_series('RCCCBBALTOT').reset_index()
data_consumercredit_pastdue = fred.get_series('RCCCBACTDPD30P').reset_index()
data_consumermortgate_originations = fred.get_series('RCMFLOORIG').reset_index()
data_consumermortgate_pastdue = fred.get_series('RCMFLBACTDPDPCT30P').reset_index()
data_consumersentiment = fred.get_series('UMCSENT').reset_index()
data_fedfundsrate = fred.get_series('FEDFUNDs').reset_index()
data_GDP

         index          0
0   1946-01-01        NaN
1   1946-04-01        NaN
2   1946-07-01        NaN
3   1946-10-01        NaN
4   1947-01-01    243.164
..         ...        ...
309 2023-04-01  27063.012
310 2023-07-01  27610.128
311 2023-10-01  27956.998
312 2024-01-01  28269.174
313 2024-04-01  28652.337

[314 rows x 2 columns]

In [85]:
#create an economic data dataframe and we will start with monthly to use for the dash
econ_data = data_GDP['index']
data_unemp_rate.columns

Index(['index', 0], dtype='object')

In [86]:
#begin df with unemp rate followed by subsequent metrics
econ_data_comb = pd.merge(econ_data,data_unemp_rate[['index',0]],how='left',on='index')

In [87]:
#rename
econd_data_comb = econ_data_comb.rename(columns={0:"unemp_rate"},inplace=True)
econ_data_comb

         index  unemp_rate
0   1946-01-01         NaN
1   1946-04-01         NaN
2   1946-07-01         NaN
3   1946-10-01         NaN
4   1947-01-01         NaN
..         ...         ...
309 2023-04-01         3.4
310 2023-07-01         3.5
311 2023-10-01         3.8
312 2024-01-01         3.7
313 2024-04-01         3.9

[314 rows x 2 columns]

In [88]:
#grab next and rename

econ_data_comb = pd.merge(econ_data_comb,data_GDP[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"GDP"},inplace=True)
econ_data_comb

         index  unemp_rate        GDP
0   1946-01-01         NaN        NaN
1   1946-04-01         NaN        NaN
2   1946-07-01         NaN        NaN
3   1946-10-01         NaN        NaN
4   1947-01-01         NaN    243.164
..         ...         ...        ...
309 2023-04-01         3.4  27063.012
310 2023-07-01         3.5  27610.128
311 2023-10-01         3.8  27956.998
312 2024-01-01         3.7  28269.174
313 2024-04-01         3.9  28652.337

[314 rows x 3 columns]

In [89]:
econ_data_comb = pd.merge(econ_data_comb,data_consumercredit[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"consumer_credit"},inplace=True)
econ_data_comb

         index  unemp_rate        GDP  consumer_credit
0   1946-01-01         NaN        NaN              NaN
1   1946-04-01         NaN        NaN              NaN
2   1946-07-01         NaN        NaN              NaN
3   1946-10-01         NaN        NaN              NaN
4   1947-01-01         NaN    243.164              NaN
..         ...         ...        ...              ...
309 2023-04-01         3.4  27063.012           838.58
310 2023-07-01         3.5  27610.128           864.60
311 2023-10-01         3.8  27956.998           911.92
312 2024-01-01         3.7  28269.174           881.23
313 2024-04-01         3.9  28652.337              NaN

[314 rows x 4 columns]

In [90]:

econ_data_comb = pd.merge(econ_data_comb,data_consumercredit_pastdue[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"consumer_credit_past_due"},inplace=True)
econ_data_comb = pd.merge(econ_data_comb,data_consumermortgate_originations[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"consumer_mortgage_orig"},inplace=True)
econ_data_comb = pd.merge(econ_data_comb,data_consumermortgate_pastdue[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"consumer_mortgage_past_due"},inplace=True)
econ_data_comb = pd.merge(econ_data_comb,data_consumersentiment[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"consumer_sentiment"},inplace=True)
econ_data_comb = pd.merge(econ_data_comb,data_fedfundsrate[['index',0]],how='left',on='index')
econ_data_comb.rename(columns={0:"fed_funds_rate"},inplace=True)

econ_data_comb

,index,unemp_rate,GDP,consumer_credit,consumer_credit_past_due,consumer_mortgage_orig,consumer_mortgage_past_due,consumer_sentiment,fed_funds_rate
0,1946-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1946-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1946-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1946-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1947-01-01,NaN,243.164,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
309,2023-04-01,3.4,27063.012,838.58,1.51,61.68,2.75,63.7,4.83
310,2023-07-01,3.5,27610.128,864.60,1.74,58.82,2.68,71.5,5.12
311,2023-10-01,3.8,27956.998,911.92,1.90,45.23,2.74,63.8,5.33
312,2024-01-01,3.7,28269.174,881.23,1.79,44.43,2.58,79.0,5.33
313,2024-04-01,3.9,28652.337,NaN,NaN,NaN,NaN,77.2,5.33

In [93]:
import sqlite3
%load_ext sql

In [105]:
simp_company_data.columns

Index(['Ticker', 'industry', 'sector', 'fullTimeEmployees', 'totalCash',
       'ebitda', 'totalDebt', 'totalRevenue', 'dividendYield', 'trailingPE',
       'forwardPE', 'averageVolume10days', 'fiftyTwoWeekLow',
       'fiftyTwoWeekHigh', 'profitMargins', 'sharesOutstanding', 'sharesShort',
       'sharesShortPriorMonth', 'heldPercentInsiders',
       'heldPercentInstitutions', 'shortRatio', 'bookValue', 'priceToBook',
       'trailingEps', 'forwardEps', 'recommendationKey', 'recommendationMean',
       'numberOfAnalystOpinions', 'returnOnEquity', 'freeCashflow',
       'operatingCashflow', 'revenueGrowth', 'grossMargins', 'ebitdaMargins',
       'operatingMargins', 'earningsQuarterlyGrowth', 'earningsGrowth'],
      dtype='object')

In [106]:
#set up connection and connect to db
con = sqlite3.connect("finance_app.db")
cur = con.cursor()
%sql sqlite:///finance_app.db

In [107]:
#convert tables into sql
%sql DROP TABLE IF EXISTS stock_price_data;
%sql DROP TABLE IF EXISTS company_data;
%sql DROP TABLE IF EXISTS econ_data;
stock_data_comb.to_sql("stock_price_data", con)
simp_company_data.to_sql("company_data", con)
econ_data_comb.to_sql("econ_data", con)

 * sqlite:///finance_app.db
Done.
 * sqlite:///finance_app.db
Done.
 * sqlite:///finance_app.db
Done.

314